# Generated by Django 4.2.23 on 2026-04-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0005_create_award_id_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDFVersionTracking',
            fields=[
                ('table_name', models.TextField(primary_key=True, serialize=False)),
                ('last_processed_version', models.BigIntegerField()),
                ('last_commit_timestamp', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cdf_version_tracking',
                'managed': True,
            },
        ),
    ]
